onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /cpu_main/CLK
add wave -noupdate -expand /cpu_main/FLAGS
add wave -noupdate -radix unsigned /cpu_main/FS_PC
add wave -noupdate -expand /cpu_main/DECODE_STAGE_INSTANCE/REG_FILE/reg_file
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/correct_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/address2
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/mux8_output
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/read_data_1
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/predicted_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/prev_IR_16_bit
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/bit_IR_16
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/hold_to_complete
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_reset
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_interrupt
add wave -noupdate /cpu_main/GLOBAL_ENABLE
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/GLOBAL_INITAIL
add wave -noupdate /cpu_main/CLK
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/FLAGS
add wave -noupdate /cpu_main/MAIN_INTERRUPT
add wave -noupdate /cpu_main/FS_IR
add wave -noupdate /cpu_main/FS_PC
add wave -noupdate /cpu_main/IFID_IR
add wave -noupdate /cpu_main/IFID_PC
add wave -noupdate /cpu_main/CU_OUT_SIG
add wave -noupdate /cpu_main/CU_IN_SIG
add wave -noupdate /cpu_main/CU_ALU_OPR
add wave -noupdate /cpu_main/CU_ALU_SRC
add wave -noupdate /cpu_main/CU_REG_DST
add wave -noupdate /cpu_main/CU_MEM_TO_REG
add wave -noupdate /cpu_main/CU_FETCH_EN
add wave -noupdate /cpu_main/CU_DATA_EN
add wave -noupdate /cpu_main/CU_ALU_EN
add wave -noupdate /cpu_main/CU_BR_EN
add wave -noupdate /cpu_main/CU_MEM_WR_EN
add wave -noupdate /cpu_main/CU_MEM_RD_EN
add wave -noupdate /cpu_main/CU_SWAP
add wave -noupdate /cpu_main/CU_IN_SP
add wave -noupdate /cpu_main/CU_SP_INC_DEC
add wave -noupdate /cpu_main/CU_EA_IMM_SEL
add wave -noupdate /cpu_main/CU_JMP
add wave -noupdate /cpu_main/CU_JZ
add wave -noupdate /cpu_main/CU_FUNC
add wave -noupdate /cpu_main/CU_RTI
add wave -noupdate /cpu_main/CU_WB
add wave -noupdate /cpu_main/CU_FLUSH_JMP
add wave -noupdate /cpu_main/CU_FLUSH_FUNC
add wave -noupdate /cpu_main/CU_FLUSH_JZ
add wave -noupdate /cpu_main/IDEX_OUT_CONTROL_SIGNALS
add wave -noupdate /cpu_main/IDEX_PC_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_OUT
add wave -noupdate /cpu_main/IDEX_EA_IMM_DATA_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_address_OUT
add wave -noupdate /cpu_main/IDEX_IR_OPCODE_OUT
add wave -noupdate /cpu_main/WB_WR_ADDRESS_1
add wave -noupdate /cpu_main/WB_WR_ADDRESS_2
add wave -noupdate /cpu_main/WB_WR_DATA_1
add wave -noupdate /cpu_main/WB_WR_DATA_2
add wave -noupdate /cpu_main/WB_WR_EN_1
add wave -noupdate /cpu_main/WB_WR_EN_2
add wave -noupdate /cpu_main/EAIMM_MUXOP_DS
add wave -noupdate /cpu_main/DS_RD_DATA_1_OUT
add wave -noupdate /cpu_main/DS_RD_DATA_2_OUT
add wave -noupdate /cpu_main/ZERO_LOGIC_16
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS
add wave -noupdate /cpu_main/EXMEM_PC
add wave -noupdate /cpu_main/EXMEM_Rdst
add wave -noupdate /cpu_main/EXMEM_Rsrc2
add wave -noupdate /cpu_main/EXMEM_Rdst_address
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address
add wave -noupdate /cpu_main/EX_MEM_OPCODE
add wave -noupdate /cpu_main/Forwarding_Selectors1
add wave -noupdate /cpu_main/Forwarding_Selectors2
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/IFID_INTR
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT_OUT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS_OUT
add wave -noupdate /cpu_main/EXMEM_PC_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address_OUT
add wave -noupdate /cpu_main/EXMEM_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutMemory
add wave -noupdate /cpu_main/RSrc2DataOutMemory
add wave -noupdate /cpu_main/RDesOutMemory
add wave -noupdate /cpu_main/RSrcOut1Memory
add wave -noupdate /cpu_main/RSrcOut2Memory
add wave -noupdate /cpu_main/MemOutMemory
add wave -noupdate /cpu_main/SPOutMemory
add wave -noupdate /cpu_main/ALUResultOutMemory
add wave -noupdate /cpu_main/ControlSignalsOutMemory
add wave -noupdate /cpu_main/MEMSTAGE_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutBuffer
add wave -noupdate /cpu_main/RSrc2DataOutBuffer
add wave -noupdate /cpu_main/RDesOutBuffer
add wave -noupdate /cpu_main/RSrcOut1Buffer
add wave -noupdate /cpu_main/RSrcOut2Buffer
add wave -noupdate /cpu_main/ControlSignalsOutBuffer
add wave -noupdate /cpu_main/SPOutBuffer
add wave -noupdate /cpu_main/MemOutBuffer
add wave -noupdate /cpu_main/ALUResultOutBuffer
add wave -noupdate /cpu_main/MEMWB_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutWB
add wave -noupdate /cpu_main/RSrc2DataOutWB
add wave -noupdate /cpu_main/RDesOutWB
add wave -noupdate /cpu_main/RSrcOut1WB
add wave -noupdate /cpu_main/RSrcOut2WB
add wave -noupdate /cpu_main/ControlSignalsOutWB
add wave -noupdate /cpu_main/Mux10OutWB
add wave -noupdate /cpu_main/SPOutWB
add wave -noupdate /cpu_main/IntOutWB
add wave -noupdate /cpu_main/SPSignal
add wave -noupdate /cpu_main/STALL_TO_FECTH_COMPELETE
add wave -noupdate /cpu_main/DS_Rdst_address
add wave -noupdate /cpu_main/DS_Rsrc1_address
add wave -noupdate /cpu_main/DS_Rsrc2_address
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/BranchFetch
add wave -noupdate /cpu_main/IS_RET
add wave -noupdate /cpu_main/IS_RTI
add wave -noupdate /cpu_main/FlagsInput
add wave -noupdate /cpu_main/ExecuteStageFlags
add wave -noupdate /cpu_main/CLK
add wave -noupdate /cpu_main/FLAGS
add wave -noupdate /cpu_main/FS_PC
add wave -noupdate /cpu_main/DECODE_STAGE_INSTANCE/REG_FILE/reg_file
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/correct_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/address2
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/mux8_output
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/read_data_1
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/predicted_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/prev_IR_16_bit
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/bit_IR_16
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/hold_to_complete
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_reset
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_interrupt
add wave -noupdate /cpu_main/GLOBAL_ENABLE
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/GLOBAL_INITAIL
add wave -noupdate /cpu_main/CLK
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/FLAGS
add wave -noupdate /cpu_main/MAIN_INTERRUPT
add wave -noupdate /cpu_main/FS_IR
add wave -noupdate /cpu_main/FS_PC
add wave -noupdate /cpu_main/IFID_IR
add wave -noupdate /cpu_main/IFID_PC
add wave -noupdate /cpu_main/CU_OUT_SIG
add wave -noupdate /cpu_main/CU_IN_SIG
add wave -noupdate /cpu_main/CU_ALU_OPR
add wave -noupdate /cpu_main/CU_ALU_SRC
add wave -noupdate /cpu_main/CU_REG_DST
add wave -noupdate /cpu_main/CU_MEM_TO_REG
add wave -noupdate /cpu_main/CU_FETCH_EN
add wave -noupdate /cpu_main/CU_DATA_EN
add wave -noupdate /cpu_main/CU_ALU_EN
add wave -noupdate /cpu_main/CU_BR_EN
add wave -noupdate /cpu_main/CU_MEM_WR_EN
add wave -noupdate /cpu_main/CU_MEM_RD_EN
add wave -noupdate /cpu_main/CU_SWAP
add wave -noupdate /cpu_main/CU_IN_SP
add wave -noupdate /cpu_main/CU_SP_INC_DEC
add wave -noupdate /cpu_main/CU_EA_IMM_SEL
add wave -noupdate /cpu_main/CU_JMP
add wave -noupdate /cpu_main/CU_JZ
add wave -noupdate /cpu_main/CU_FUNC
add wave -noupdate /cpu_main/CU_RTI
add wave -noupdate /cpu_main/CU_WB
add wave -noupdate /cpu_main/CU_FLUSH_JMP
add wave -noupdate /cpu_main/CU_FLUSH_FUNC
add wave -noupdate /cpu_main/CU_FLUSH_JZ
add wave -noupdate /cpu_main/IDEX_OUT_CONTROL_SIGNALS
add wave -noupdate /cpu_main/IDEX_PC_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_OUT
add wave -noupdate /cpu_main/IDEX_EA_IMM_DATA_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_address_OUT
add wave -noupdate /cpu_main/IDEX_IR_OPCODE_OUT
add wave -noupdate /cpu_main/WB_WR_ADDRESS_1
add wave -noupdate /cpu_main/WB_WR_ADDRESS_2
add wave -noupdate /cpu_main/WB_WR_DATA_1
add wave -noupdate /cpu_main/WB_WR_DATA_2
add wave -noupdate /cpu_main/WB_WR_EN_1
add wave -noupdate /cpu_main/WB_WR_EN_2
add wave -noupdate /cpu_main/EAIMM_MUXOP_DS
add wave -noupdate /cpu_main/DS_RD_DATA_1_OUT
add wave -noupdate /cpu_main/DS_RD_DATA_2_OUT
add wave -noupdate /cpu_main/ZERO_LOGIC_16
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS
add wave -noupdate /cpu_main/EXMEM_PC
add wave -noupdate /cpu_main/EXMEM_Rdst
add wave -noupdate /cpu_main/EXMEM_Rsrc2
add wave -noupdate /cpu_main/EXMEM_Rdst_address
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address
add wave -noupdate /cpu_main/EX_MEM_OPCODE
add wave -noupdate /cpu_main/Forwarding_Selectors1
add wave -noupdate /cpu_main/Forwarding_Selectors2
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/IFID_INTR
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT_OUT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS_OUT
add wave -noupdate /cpu_main/EXMEM_PC_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address_OUT
add wave -noupdate /cpu_main/EXMEM_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutMemory
add wave -noupdate /cpu_main/RSrc2DataOutMemory
add wave -noupdate /cpu_main/RDesOutMemory
add wave -noupdate /cpu_main/RSrcOut1Memory
add wave -noupdate /cpu_main/RSrcOut2Memory
add wave -noupdate /cpu_main/MemOutMemory
add wave -noupdate /cpu_main/SPOutMemory
add wave -noupdate /cpu_main/ALUResultOutMemory
add wave -noupdate /cpu_main/ControlSignalsOutMemory
add wave -noupdate /cpu_main/MEMSTAGE_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutBuffer
add wave -noupdate /cpu_main/RSrc2DataOutBuffer
add wave -noupdate /cpu_main/RDesOutBuffer
add wave -noupdate /cpu_main/RSrcOut1Buffer
add wave -noupdate /cpu_main/RSrcOut2Buffer
add wave -noupdate /cpu_main/ControlSignalsOutBuffer
add wave -noupdate /cpu_main/SPOutBuffer
add wave -noupdate /cpu_main/MemOutBuffer
add wave -noupdate /cpu_main/ALUResultOutBuffer
add wave -noupdate /cpu_main/MEMWB_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutWB
add wave -noupdate /cpu_main/RSrc2DataOutWB
add wave -noupdate /cpu_main/RDesOutWB
add wave -noupdate /cpu_main/RSrcOut1WB
add wave -noupdate /cpu_main/RSrcOut2WB
add wave -noupdate /cpu_main/ControlSignalsOutWB
add wave -noupdate /cpu_main/Mux10OutWB
add wave -noupdate /cpu_main/SPOutWB
add wave -noupdate /cpu_main/IntOutWB
add wave -noupdate /cpu_main/SPSignal
add wave -noupdate /cpu_main/STALL_TO_FECTH_COMPELETE
add wave -noupdate /cpu_main/DS_Rdst_address
add wave -noupdate /cpu_main/DS_Rsrc1_address
add wave -noupdate /cpu_main/DS_Rsrc2_address
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/BranchFetch
add wave -noupdate /cpu_main/IS_RET
add wave -noupdate /cpu_main/IS_RTI
add wave -noupdate /cpu_main/FlagsInput
add wave -noupdate /cpu_main/ExecuteStageFlags
add wave -noupdate /cpu_main/CLK
add wave -noupdate /cpu_main/FLAGS
add wave -noupdate /cpu_main/FS_PC
add wave -noupdate /cpu_main/DECODE_STAGE_INSTANCE/REG_FILE/reg_file
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/correct_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/address2
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/mux8_output
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/read_data_1
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/predicted_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/prev_IR_16_bit
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/bit_IR_16
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/hold_to_complete
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_reset
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_interrupt
add wave -noupdate /cpu_main/GLOBAL_ENABLE
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/GLOBAL_INITAIL
add wave -noupdate /cpu_main/CLK
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/FLAGS
add wave -noupdate /cpu_main/MAIN_INTERRUPT
add wave -noupdate /cpu_main/FS_IR
add wave -noupdate /cpu_main/FS_PC
add wave -noupdate /cpu_main/IFID_IR
add wave -noupdate /cpu_main/IFID_PC
add wave -noupdate /cpu_main/CU_OUT_SIG
add wave -noupdate /cpu_main/CU_IN_SIG
add wave -noupdate /cpu_main/CU_ALU_OPR
add wave -noupdate /cpu_main/CU_ALU_SRC
add wave -noupdate /cpu_main/CU_REG_DST
add wave -noupdate /cpu_main/CU_MEM_TO_REG
add wave -noupdate /cpu_main/CU_FETCH_EN
add wave -noupdate /cpu_main/CU_DATA_EN
add wave -noupdate /cpu_main/CU_ALU_EN
add wave -noupdate /cpu_main/CU_BR_EN
add wave -noupdate /cpu_main/CU_MEM_WR_EN
add wave -noupdate /cpu_main/CU_MEM_RD_EN
add wave -noupdate /cpu_main/CU_SWAP
add wave -noupdate /cpu_main/CU_IN_SP
add wave -noupdate /cpu_main/CU_SP_INC_DEC
add wave -noupdate /cpu_main/CU_EA_IMM_SEL
add wave -noupdate /cpu_main/CU_JMP
add wave -noupdate /cpu_main/CU_JZ
add wave -noupdate /cpu_main/CU_FUNC
add wave -noupdate /cpu_main/CU_RTI
add wave -noupdate /cpu_main/CU_WB
add wave -noupdate /cpu_main/CU_FLUSH_JMP
add wave -noupdate /cpu_main/CU_FLUSH_FUNC
add wave -noupdate /cpu_main/CU_FLUSH_JZ
add wave -noupdate /cpu_main/IDEX_OUT_CONTROL_SIGNALS
add wave -noupdate /cpu_main/IDEX_PC_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_OUT
add wave -noupdate /cpu_main/IDEX_EA_IMM_DATA_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_address_OUT
add wave -noupdate /cpu_main/IDEX_IR_OPCODE_OUT
add wave -noupdate /cpu_main/WB_WR_ADDRESS_1
add wave -noupdate /cpu_main/WB_WR_ADDRESS_2
add wave -noupdate /cpu_main/WB_WR_DATA_1
add wave -noupdate /cpu_main/WB_WR_DATA_2
add wave -noupdate /cpu_main/WB_WR_EN_1
add wave -noupdate /cpu_main/WB_WR_EN_2
add wave -noupdate /cpu_main/EAIMM_MUXOP_DS
add wave -noupdate /cpu_main/DS_RD_DATA_1_OUT
add wave -noupdate /cpu_main/DS_RD_DATA_2_OUT
add wave -noupdate /cpu_main/ZERO_LOGIC_16
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS
add wave -noupdate /cpu_main/EXMEM_PC
add wave -noupdate /cpu_main/EXMEM_Rdst
add wave -noupdate /cpu_main/EXMEM_Rsrc2
add wave -noupdate /cpu_main/EXMEM_Rdst_address
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address
add wave -noupdate /cpu_main/EX_MEM_OPCODE
add wave -noupdate /cpu_main/Forwarding_Selectors1
add wave -noupdate /cpu_main/Forwarding_Selectors2
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/IFID_INTR
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT_OUT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS_OUT
add wave -noupdate /cpu_main/EXMEM_PC_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address_OUT
add wave -noupdate /cpu_main/EXMEM_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutMemory
add wave -noupdate /cpu_main/RSrc2DataOutMemory
add wave -noupdate /cpu_main/RDesOutMemory
add wave -noupdate /cpu_main/RSrcOut1Memory
add wave -noupdate /cpu_main/RSrcOut2Memory
add wave -noupdate /cpu_main/MemOutMemory
add wave -noupdate /cpu_main/SPOutMemory
add wave -noupdate /cpu_main/ALUResultOutMemory
add wave -noupdate /cpu_main/ControlSignalsOutMemory
add wave -noupdate /cpu_main/MEMSTAGE_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutBuffer
add wave -noupdate /cpu_main/RSrc2DataOutBuffer
add wave -noupdate /cpu_main/RDesOutBuffer
add wave -noupdate /cpu_main/RSrcOut1Buffer
add wave -noupdate /cpu_main/RSrcOut2Buffer
add wave -noupdate /cpu_main/ControlSignalsOutBuffer
add wave -noupdate /cpu_main/SPOutBuffer
add wave -noupdate /cpu_main/MemOutBuffer
add wave -noupdate /cpu_main/ALUResultOutBuffer
add wave -noupdate /cpu_main/MEMWB_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutWB
add wave -noupdate /cpu_main/RSrc2DataOutWB
add wave -noupdate /cpu_main/RDesOutWB
add wave -noupdate /cpu_main/RSrcOut1WB
add wave -noupdate /cpu_main/RSrcOut2WB
add wave -noupdate /cpu_main/ControlSignalsOutWB
add wave -noupdate /cpu_main/Mux10OutWB
add wave -noupdate /cpu_main/SPOutWB
add wave -noupdate /cpu_main/IntOutWB
add wave -noupdate /cpu_main/SPSignal
add wave -noupdate /cpu_main/STALL_TO_FECTH_COMPELETE
add wave -noupdate /cpu_main/DS_Rdst_address
add wave -noupdate /cpu_main/DS_Rsrc1_address
add wave -noupdate /cpu_main/DS_Rsrc2_address
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/BranchFetch
add wave -noupdate /cpu_main/IS_RET
add wave -noupdate /cpu_main/IS_RTI
add wave -noupdate /cpu_main/FlagsInput
add wave -noupdate /cpu_main/ExecuteStageFlags
add wave -noupdate /cpu_main/CLK
add wave -noupdate /cpu_main/FLAGS
add wave -noupdate /cpu_main/FS_PC
add wave -noupdate /cpu_main/DECODE_STAGE_INSTANCE/REG_FILE/reg_file
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/correct_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/address2
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/mux8_output
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/read_data_1
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/predicted_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/prev_IR_16_bit
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/bit_IR_16
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/hold_to_complete
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_reset
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_interrupt
add wave -noupdate /cpu_main/GLOBAL_ENABLE
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/GLOBAL_INITAIL
add wave -noupdate /cpu_main/CLK
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/FLAGS
add wave -noupdate /cpu_main/MAIN_INTERRUPT
add wave -noupdate /cpu_main/FS_IR
add wave -noupdate /cpu_main/FS_PC
add wave -noupdate /cpu_main/IFID_IR
add wave -noupdate /cpu_main/IFID_PC
add wave -noupdate /cpu_main/CU_OUT_SIG
add wave -noupdate /cpu_main/CU_IN_SIG
add wave -noupdate /cpu_main/CU_ALU_OPR
add wave -noupdate /cpu_main/CU_ALU_SRC
add wave -noupdate /cpu_main/CU_REG_DST
add wave -noupdate /cpu_main/CU_MEM_TO_REG
add wave -noupdate /cpu_main/CU_FETCH_EN
add wave -noupdate /cpu_main/CU_DATA_EN
add wave -noupdate /cpu_main/CU_ALU_EN
add wave -noupdate /cpu_main/CU_BR_EN
add wave -noupdate /cpu_main/CU_MEM_WR_EN
add wave -noupdate /cpu_main/CU_MEM_RD_EN
add wave -noupdate /cpu_main/CU_SWAP
add wave -noupdate /cpu_main/CU_IN_SP
add wave -noupdate /cpu_main/CU_SP_INC_DEC
add wave -noupdate /cpu_main/CU_EA_IMM_SEL
add wave -noupdate /cpu_main/CU_JMP
add wave -noupdate /cpu_main/CU_JZ
add wave -noupdate /cpu_main/CU_FUNC
add wave -noupdate /cpu_main/CU_RTI
add wave -noupdate /cpu_main/CU_WB
add wave -noupdate /cpu_main/CU_FLUSH_JMP
add wave -noupdate /cpu_main/CU_FLUSH_FUNC
add wave -noupdate /cpu_main/CU_FLUSH_JZ
add wave -noupdate /cpu_main/IDEX_OUT_CONTROL_SIGNALS
add wave -noupdate /cpu_main/IDEX_PC_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_OUT
add wave -noupdate /cpu_main/IDEX_EA_IMM_DATA_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_address_OUT
add wave -noupdate /cpu_main/IDEX_IR_OPCODE_OUT
add wave -noupdate /cpu_main/WB_WR_ADDRESS_1
add wave -noupdate /cpu_main/WB_WR_ADDRESS_2
add wave -noupdate /cpu_main/WB_WR_DATA_1
add wave -noupdate /cpu_main/WB_WR_DATA_2
add wave -noupdate /cpu_main/WB_WR_EN_1
add wave -noupdate /cpu_main/WB_WR_EN_2
add wave -noupdate /cpu_main/EAIMM_MUXOP_DS
add wave -noupdate /cpu_main/DS_RD_DATA_1_OUT
add wave -noupdate /cpu_main/DS_RD_DATA_2_OUT
add wave -noupdate /cpu_main/ZERO_LOGIC_16
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS
add wave -noupdate /cpu_main/EXMEM_PC
add wave -noupdate /cpu_main/EXMEM_Rdst
add wave -noupdate /cpu_main/EXMEM_Rsrc2
add wave -noupdate /cpu_main/EXMEM_Rdst_address
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address
add wave -noupdate /cpu_main/EX_MEM_OPCODE
add wave -noupdate /cpu_main/Forwarding_Selectors1
add wave -noupdate /cpu_main/Forwarding_Selectors2
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/IFID_INTR
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT_OUT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS_OUT
add wave -noupdate /cpu_main/EXMEM_PC_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address_OUT
add wave -noupdate /cpu_main/EXMEM_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutMemory
add wave -noupdate /cpu_main/RSrc2DataOutMemory
add wave -noupdate /cpu_main/RDesOutMemory
add wave -noupdate /cpu_main/RSrcOut1Memory
add wave -noupdate /cpu_main/RSrcOut2Memory
add wave -noupdate /cpu_main/MemOutMemory
add wave -noupdate /cpu_main/SPOutMemory
add wave -noupdate /cpu_main/ALUResultOutMemory
add wave -noupdate /cpu_main/ControlSignalsOutMemory
add wave -noupdate /cpu_main/MEMSTAGE_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutBuffer
add wave -noupdate /cpu_main/RSrc2DataOutBuffer
add wave -noupdate /cpu_main/RDesOutBuffer
add wave -noupdate /cpu_main/RSrcOut1Buffer
add wave -noupdate /cpu_main/RSrcOut2Buffer
add wave -noupdate /cpu_main/ControlSignalsOutBuffer
add wave -noupdate /cpu_main/SPOutBuffer
add wave -noupdate /cpu_main/MemOutBuffer
add wave -noupdate /cpu_main/ALUResultOutBuffer
add wave -noupdate /cpu_main/MEMWB_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutWB
add wave -noupdate /cpu_main/RSrc2DataOutWB
add wave -noupdate /cpu_main/RDesOutWB
add wave -noupdate /cpu_main/RSrcOut1WB
add wave -noupdate /cpu_main/RSrcOut2WB
add wave -noupdate /cpu_main/ControlSignalsOutWB
add wave -noupdate /cpu_main/Mux10OutWB
add wave -noupdate /cpu_main/SPOutWB
add wave -noupdate /cpu_main/IntOutWB
add wave -noupdate /cpu_main/SPSignal
add wave -noupdate /cpu_main/STALL_TO_FECTH_COMPELETE
add wave -noupdate /cpu_main/DS_Rdst_address
add wave -noupdate /cpu_main/DS_Rsrc1_address
add wave -noupdate /cpu_main/DS_Rsrc2_address
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/BranchFetch
add wave -noupdate /cpu_main/IS_RET
add wave -noupdate /cpu_main/IS_RTI
add wave -noupdate /cpu_main/FlagsInput
add wave -noupdate /cpu_main/ExecuteStageFlags
add wave -noupdate /cpu_main/CLK
add wave -noupdate /cpu_main/FLAGS
add wave -noupdate /cpu_main/FS_PC
add wave -noupdate /cpu_main/DECODE_STAGE_INSTANCE/REG_FILE/reg_file
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/correct_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/address2
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/mux8_output
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/read_data_1
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/predicted_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/prev_IR_16_bit
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/bit_IR_16
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/hold_to_complete
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_reset
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_interrupt
add wave -noupdate /cpu_main/GLOBAL_ENABLE
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/GLOBAL_INITAIL
add wave -noupdate /cpu_main/CLK
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/FLAGS
add wave -noupdate /cpu_main/MAIN_INTERRUPT
add wave -noupdate /cpu_main/FS_IR
add wave -noupdate /cpu_main/FS_PC
add wave -noupdate /cpu_main/IFID_IR
add wave -noupdate /cpu_main/IFID_PC
add wave -noupdate /cpu_main/CU_OUT_SIG
add wave -noupdate /cpu_main/CU_IN_SIG
add wave -noupdate /cpu_main/CU_ALU_OPR
add wave -noupdate /cpu_main/CU_ALU_SRC
add wave -noupdate /cpu_main/CU_REG_DST
add wave -noupdate /cpu_main/CU_MEM_TO_REG
add wave -noupdate /cpu_main/CU_FETCH_EN
add wave -noupdate /cpu_main/CU_DATA_EN
add wave -noupdate /cpu_main/CU_ALU_EN
add wave -noupdate /cpu_main/CU_BR_EN
add wave -noupdate /cpu_main/CU_MEM_WR_EN
add wave -noupdate /cpu_main/CU_MEM_RD_EN
add wave -noupdate /cpu_main/CU_SWAP
add wave -noupdate /cpu_main/CU_IN_SP
add wave -noupdate /cpu_main/CU_SP_INC_DEC
add wave -noupdate /cpu_main/CU_EA_IMM_SEL
add wave -noupdate /cpu_main/CU_JMP
add wave -noupdate /cpu_main/CU_JZ
add wave -noupdate /cpu_main/CU_FUNC
add wave -noupdate /cpu_main/CU_RTI
add wave -noupdate /cpu_main/CU_WB
add wave -noupdate /cpu_main/CU_FLUSH_JMP
add wave -noupdate /cpu_main/CU_FLUSH_FUNC
add wave -noupdate /cpu_main/CU_FLUSH_JZ
add wave -noupdate /cpu_main/IDEX_OUT_CONTROL_SIGNALS
add wave -noupdate /cpu_main/IDEX_PC_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_OUT
add wave -noupdate /cpu_main/IDEX_EA_IMM_DATA_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_address_OUT
add wave -noupdate /cpu_main/IDEX_IR_OPCODE_OUT
add wave -noupdate /cpu_main/WB_WR_ADDRESS_1
add wave -noupdate /cpu_main/WB_WR_ADDRESS_2
add wave -noupdate /cpu_main/WB_WR_DATA_1
add wave -noupdate /cpu_main/WB_WR_DATA_2
add wave -noupdate /cpu_main/WB_WR_EN_1
add wave -noupdate /cpu_main/WB_WR_EN_2
add wave -noupdate /cpu_main/EAIMM_MUXOP_DS
add wave -noupdate /cpu_main/DS_RD_DATA_1_OUT
add wave -noupdate /cpu_main/DS_RD_DATA_2_OUT
add wave -noupdate /cpu_main/ZERO_LOGIC_16
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS
add wave -noupdate /cpu_main/EXMEM_PC
add wave -noupdate /cpu_main/EXMEM_Rdst
add wave -noupdate /cpu_main/EXMEM_Rsrc2
add wave -noupdate /cpu_main/EXMEM_Rdst_address
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address
add wave -noupdate /cpu_main/EX_MEM_OPCODE
add wave -noupdate /cpu_main/Forwarding_Selectors1
add wave -noupdate /cpu_main/Forwarding_Selectors2
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/IFID_INTR
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT_OUT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS_OUT
add wave -noupdate /cpu_main/EXMEM_PC_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address_OUT
add wave -noupdate /cpu_main/EXMEM_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutMemory
add wave -noupdate /cpu_main/RSrc2DataOutMemory
add wave -noupdate /cpu_main/RDesOutMemory
add wave -noupdate /cpu_main/RSrcOut1Memory
add wave -noupdate /cpu_main/RSrcOut2Memory
add wave -noupdate /cpu_main/MemOutMemory
add wave -noupdate /cpu_main/SPOutMemory
add wave -noupdate /cpu_main/ALUResultOutMemory
add wave -noupdate /cpu_main/ControlSignalsOutMemory
add wave -noupdate /cpu_main/MEMSTAGE_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutBuffer
add wave -noupdate /cpu_main/RSrc2DataOutBuffer
add wave -noupdate /cpu_main/RDesOutBuffer
add wave -noupdate /cpu_main/RSrcOut1Buffer
add wave -noupdate /cpu_main/RSrcOut2Buffer
add wave -noupdate /cpu_main/ControlSignalsOutBuffer
add wave -noupdate /cpu_main/SPOutBuffer
add wave -noupdate /cpu_main/MemOutBuffer
add wave -noupdate /cpu_main/ALUResultOutBuffer
add wave -noupdate /cpu_main/MEMWB_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutWB
add wave -noupdate /cpu_main/RSrc2DataOutWB
add wave -noupdate /cpu_main/RDesOutWB
add wave -noupdate /cpu_main/RSrcOut1WB
add wave -noupdate /cpu_main/RSrcOut2WB
add wave -noupdate /cpu_main/ControlSignalsOutWB
add wave -noupdate /cpu_main/Mux10OutWB
add wave -noupdate /cpu_main/SPOutWB
add wave -noupdate /cpu_main/IntOutWB
add wave -noupdate /cpu_main/SPSignal
add wave -noupdate /cpu_main/STALL_TO_FECTH_COMPELETE
add wave -noupdate /cpu_main/DS_Rdst_address
add wave -noupdate /cpu_main/DS_Rsrc1_address
add wave -noupdate /cpu_main/DS_Rsrc2_address
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/BranchFetch
add wave -noupdate /cpu_main/IS_RET
add wave -noupdate /cpu_main/IS_RTI
add wave -noupdate /cpu_main/FlagsInput
add wave -noupdate /cpu_main/ExecuteStageFlags
add wave -noupdate /cpu_main/CLK
add wave -noupdate /cpu_main/FLAGS
add wave -noupdate /cpu_main/FS_PC
add wave -noupdate /cpu_main/DECODE_STAGE_INSTANCE/REG_FILE/reg_file
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/correct_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/address2
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/mux8_output
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/read_data_1
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/predicted_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/prev_IR_16_bit
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/bit_IR_16
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/hold_to_complete
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_reset
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_interrupt
add wave -noupdate /cpu_main/GLOBAL_ENABLE
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/GLOBAL_INITAIL
add wave -noupdate /cpu_main/CLK
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/FLAGS
add wave -noupdate /cpu_main/MAIN_INTERRUPT
add wave -noupdate /cpu_main/FS_IR
add wave -noupdate /cpu_main/FS_PC
add wave -noupdate /cpu_main/IFID_IR
add wave -noupdate /cpu_main/IFID_PC
add wave -noupdate /cpu_main/CU_OUT_SIG
add wave -noupdate /cpu_main/CU_IN_SIG
add wave -noupdate /cpu_main/CU_ALU_OPR
add wave -noupdate /cpu_main/CU_ALU_SRC
add wave -noupdate /cpu_main/CU_REG_DST
add wave -noupdate /cpu_main/CU_MEM_TO_REG
add wave -noupdate /cpu_main/CU_FETCH_EN
add wave -noupdate /cpu_main/CU_DATA_EN
add wave -noupdate /cpu_main/CU_ALU_EN
add wave -noupdate /cpu_main/CU_BR_EN
add wave -noupdate /cpu_main/CU_MEM_WR_EN
add wave -noupdate /cpu_main/CU_MEM_RD_EN
add wave -noupdate /cpu_main/CU_SWAP
add wave -noupdate /cpu_main/CU_IN_SP
add wave -noupdate /cpu_main/CU_SP_INC_DEC
add wave -noupdate /cpu_main/CU_EA_IMM_SEL
add wave -noupdate /cpu_main/CU_JMP
add wave -noupdate /cpu_main/CU_JZ
add wave -noupdate /cpu_main/CU_FUNC
add wave -noupdate /cpu_main/CU_RTI
add wave -noupdate /cpu_main/CU_WB
add wave -noupdate /cpu_main/CU_FLUSH_JMP
add wave -noupdate /cpu_main/CU_FLUSH_FUNC
add wave -noupdate /cpu_main/CU_FLUSH_JZ
add wave -noupdate /cpu_main/IDEX_OUT_CONTROL_SIGNALS
add wave -noupdate /cpu_main/IDEX_PC_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_OUT
add wave -noupdate /cpu_main/IDEX_EA_IMM_DATA_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_address_OUT
add wave -noupdate /cpu_main/IDEX_IR_OPCODE_OUT
add wave -noupdate /cpu_main/WB_WR_ADDRESS_1
add wave -noupdate /cpu_main/WB_WR_ADDRESS_2
add wave -noupdate /cpu_main/WB_WR_DATA_1
add wave -noupdate /cpu_main/WB_WR_DATA_2
add wave -noupdate /cpu_main/WB_WR_EN_1
add wave -noupdate /cpu_main/WB_WR_EN_2
add wave -noupdate /cpu_main/EAIMM_MUXOP_DS
add wave -noupdate /cpu_main/DS_RD_DATA_1_OUT
add wave -noupdate /cpu_main/DS_RD_DATA_2_OUT
add wave -noupdate /cpu_main/ZERO_LOGIC_16
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS
add wave -noupdate /cpu_main/EXMEM_PC
add wave -noupdate /cpu_main/EXMEM_Rdst
add wave -noupdate /cpu_main/EXMEM_Rsrc2
add wave -noupdate /cpu_main/EXMEM_Rdst_address
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address
add wave -noupdate /cpu_main/EX_MEM_OPCODE
add wave -noupdate /cpu_main/Forwarding_Selectors1
add wave -noupdate /cpu_main/Forwarding_Selectors2
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/IFID_INTR
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT_OUT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS_OUT
add wave -noupdate /cpu_main/EXMEM_PC_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address_OUT
add wave -noupdate /cpu_main/EXMEM_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutMemory
add wave -noupdate /cpu_main/RSrc2DataOutMemory
add wave -noupdate /cpu_main/RDesOutMemory
add wave -noupdate /cpu_main/RSrcOut1Memory
add wave -noupdate /cpu_main/RSrcOut2Memory
add wave -noupdate /cpu_main/MemOutMemory
add wave -noupdate /cpu_main/SPOutMemory
add wave -noupdate /cpu_main/ALUResultOutMemory
add wave -noupdate /cpu_main/ControlSignalsOutMemory
add wave -noupdate /cpu_main/MEMSTAGE_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutBuffer
add wave -noupdate /cpu_main/RSrc2DataOutBuffer
add wave -noupdate /cpu_main/RDesOutBuffer
add wave -noupdate /cpu_main/RSrcOut1Buffer
add wave -noupdate /cpu_main/RSrcOut2Buffer
add wave -noupdate /cpu_main/ControlSignalsOutBuffer
add wave -noupdate /cpu_main/SPOutBuffer
add wave -noupdate /cpu_main/MemOutBuffer
add wave -noupdate /cpu_main/ALUResultOutBuffer
add wave -noupdate /cpu_main/MEMWB_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutWB
add wave -noupdate /cpu_main/RSrc2DataOutWB
add wave -noupdate /cpu_main/RDesOutWB
add wave -noupdate /cpu_main/RSrcOut1WB
add wave -noupdate /cpu_main/RSrcOut2WB
add wave -noupdate /cpu_main/ControlSignalsOutWB
add wave -noupdate /cpu_main/Mux10OutWB
add wave -noupdate /cpu_main/SPOutWB
add wave -noupdate /cpu_main/IntOutWB
add wave -noupdate /cpu_main/SPSignal
add wave -noupdate /cpu_main/STALL_TO_FECTH_COMPELETE
add wave -noupdate /cpu_main/DS_Rdst_address
add wave -noupdate /cpu_main/DS_Rsrc1_address
add wave -noupdate /cpu_main/DS_Rsrc2_address
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/BranchFetch
add wave -noupdate /cpu_main/IS_RET
add wave -noupdate /cpu_main/IS_RTI
add wave -noupdate /cpu_main/FlagsInput
add wave -noupdate /cpu_main/ExecuteStageFlags
add wave -noupdate /cpu_main/CLK
add wave -noupdate /cpu_main/FLAGS
add wave -noupdate /cpu_main/FS_PC
add wave -noupdate /cpu_main/DECODE_STAGE_INSTANCE/REG_FILE/reg_file
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/correct_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/address2
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/mux8_output
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/read_data_1
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/predicted_branch_address
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/out_PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/IR
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/prev_IR_16_bit
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/bit_IR_16
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/PC
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/hold_to_complete
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_reset
add wave -noupdate /cpu_main/FETCH_STAGE_INSTANCE/is_interrupt
add wave -noupdate /cpu_main/GLOBAL_ENABLE
add wave -noupdate /cpu_main/GLOBAL_RESET
add wave -noupdate /cpu_main/GLOBAL_INITAIL
add wave -noupdate /cpu_main/CLK
add wave -noupdate /cpu_main/OUTPORT
add wave -noupdate /cpu_main/FLAGS
add wave -noupdate /cpu_main/MAIN_INTERRUPT
add wave -noupdate /cpu_main/FS_IR
add wave -noupdate /cpu_main/FS_PC
add wave -noupdate /cpu_main/IFID_IR
add wave -noupdate /cpu_main/IFID_PC
add wave -noupdate /cpu_main/CU_OUT_SIG
add wave -noupdate /cpu_main/CU_IN_SIG
add wave -noupdate /cpu_main/CU_ALU_OPR
add wave -noupdate /cpu_main/CU_ALU_SRC
add wave -noupdate /cpu_main/CU_REG_DST
add wave -noupdate /cpu_main/CU_MEM_TO_REG
add wave -noupdate /cpu_main/CU_FETCH_EN
add wave -noupdate /cpu_main/CU_DATA_EN
add wave -noupdate /cpu_main/CU_ALU_EN
add wave -noupdate /cpu_main/CU_BR_EN
add wave -noupdate /cpu_main/CU_MEM_WR_EN
add wave -noupdate /cpu_main/CU_MEM_RD_EN
add wave -noupdate /cpu_main/CU_SWAP
add wave -noupdate /cpu_main/CU_IN_SP
add wave -noupdate /cpu_main/CU_SP_INC_DEC
add wave -noupdate /cpu_main/CU_EA_IMM_SEL
add wave -noupdate /cpu_main/CU_JMP
add wave -noupdate /cpu_main/CU_JZ
add wave -noupdate /cpu_main/CU_FUNC
add wave -noupdate /cpu_main/CU_RTI
add wave -noupdate /cpu_main/CU_WB
add wave -noupdate /cpu_main/CU_FLUSH_JMP
add wave -noupdate /cpu_main/CU_FLUSH_FUNC
add wave -noupdate /cpu_main/CU_FLUSH_JZ
add wave -noupdate /cpu_main/IDEX_OUT_CONTROL_SIGNALS
add wave -noupdate /cpu_main/IDEX_PC_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_OUT
add wave -noupdate /cpu_main/IDEX_EA_IMM_DATA_OUT
add wave -noupdate /cpu_main/IDEX_Rdst_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc1_address_OUT
add wave -noupdate /cpu_main/IDEX_Rsrc2_address_OUT
add wave -noupdate /cpu_main/IDEX_IR_OPCODE_OUT
add wave -noupdate /cpu_main/WB_WR_ADDRESS_1
add wave -noupdate /cpu_main/WB_WR_ADDRESS_2
add wave -noupdate /cpu_main/WB_WR_DATA_1
add wave -noupdate /cpu_main/WB_WR_DATA_2
add wave -noupdate /cpu_main/WB_WR_EN_1
add wave -noupdate /cpu_main/WB_WR_EN_2
add wave -noupdate /cpu_main/EAIMM_MUXOP_DS
add wave -noupdate /cpu_main/DS_RD_DATA_1_OUT
add wave -noupdate /cpu_main/DS_RD_DATA_2_OUT
add wave -noupdate /cpu_main/ZERO_LOGIC_16
add wave -noupdate /cpu_main/Hazard_Detection_Stall
add wave -noupdate /cpu_main/Hazard_Detection_IF_ID_WR_EN
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS
add wave -noupdate /cpu_main/EXMEM_PC
add wave -noupdate /cpu_main/EXMEM_Rdst
add wave -noupdate /cpu_main/EXMEM_Rsrc2
add wave -noupdate /cpu_main/EXMEM_Rdst_address
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address
add wave -noupdate /cpu_main/EX_MEM_OPCODE
add wave -noupdate /cpu_main/Forwarding_Selectors1
add wave -noupdate /cpu_main/Forwarding_Selectors2
add wave -noupdate /cpu_main/In_Port
add wave -noupdate /cpu_main/IFID_INTR
add wave -noupdate /cpu_main/EXMEM_ALU_RESULT_OUT
add wave -noupdate /cpu_main/EXMEM_CONTROL_SIGNALS_OUT
add wave -noupdate /cpu_main/EXMEM_PC_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_OUT
add wave -noupdate /cpu_main/EXMEM_Rdst_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc1_address_OUT
add wave -noupdate /cpu_main/EXMEM_Rsrc2_address_OUT
add wave -noupdate /cpu_main/EXMEM_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutMemory
add wave -noupdate /cpu_main/RSrc2DataOutMemory
add wave -noupdate /cpu_main/RDesOutMemory
add wave -noupdate /cpu_main/RSrcOut1Memory
add wave -noupdate /cpu_main/RSrcOut2Memory
add wave -noupdate /cpu_main/MemOutMemory
add wave -noupdate /cpu_main/SPOutMemory
add wave -noupdate /cpu_main/ALUResultOutMemory
add wave -noupdate /cpu_main/ControlSignalsOutMemory
add wave -noupdate /cpu_main/MEMSTAGE_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutBuffer
add wave -noupdate /cpu_main/RSrc2DataOutBuffer
add wave -noupdate /cpu_main/RDesOutBuffer
add wave -noupdate /cpu_main/RSrcOut1Buffer
add wave -noupdate /cpu_main/RSrcOut2Buffer
add wave -noupdate /cpu_main/ControlSignalsOutBuffer
add wave -noupdate /cpu_main/SPOutBuffer
add wave -noupdate /cpu_main/MemOutBuffer
add wave -noupdate /cpu_main/ALUResultOutBuffer
add wave -noupdate /cpu_main/MEMWB_OPCODE_OUT
add wave -noupdate /cpu_main/RDesDataOutWB
add wave -noupdate /cpu_main/RSrc2DataOutWB
add wave -noupdate /cpu_main/RDesOutWB
add wave -noupdate /cpu_main/RSrcOut1WB
add wave -noupdate /cpu_main/RSrcOut2WB
add wave -noupdate /cpu_main/ControlSignalsOutWB
add wave -noupdate /cpu_main/Mux10OutWB
add wave -noupdate /cpu_main/SPOutWB
add wave -noupdate /cpu_main/IntOutWB
add wave -noupdate /cpu_main/SPSignal
add wave -noupdate /cpu_main/STALL_TO_FECTH_COMPELETE
add wave -noupdate /cpu_main/DS_Rdst_address
add wave -noupdate /cpu_main/DS_Rsrc1_address
add wave -noupdate /cpu_main/DS_Rsrc2_address
add wave -noupdate /cpu_main/SPSofyan
add wave -noupdate /cpu_main/BranchFetch
add wave -noupdate /cpu_main/IS_RET
add wave -noupdate /cpu_main/IS_RTI
add wave -noupdate /cpu_main/FlagsInput
add wave -noupdate /cpu_main/ExecuteStageFlags
TreeUpdate [SetDefaultTree]
WaveRestoreCursors
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {1624 ns}
